config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :pastes
  resources :users
  resources :sessions, only: %i[new create destroy]
  get '/signin', to: 'sessions#new'
  get '/signup', to: 'users#new'
  root 'pastes#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  has_many :pastes
  validates_presence_of :username, :email, :password_digest
  validates_uniqueness_of :username, :email
  validates :password, confirmation: { case_sensitive: true }

  # a superuser account with admin = false is not valid,
  # since superuser is a subset of admin
  validates_inclusion_of :admin, in: [true], if: :superuser, message: 'must also be checked for a superuser account'
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Users Controller controls user data
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :check_if_editing_admin, only: %i[edit update destroy]
  before_action :check_admin_permission, only: :index
  before_action :check_admin_or_self_permission, except: %i[index new create]
  skip_before_action :authenticate, only: %i[new create]
  # GET /users
  def index
    query = {
      username: params[:username].presence
    }.compact
    @users = search_query(query, params[:page].to_i || 0)
  end

  # GET /users/1
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html do
          flash[:notice] = t('forms.messages.registration_successful')
          redirect_to_index
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  def update
    respond_to do |format|
      if update_user(user_params) # this contraption means 'accept updates without password'
        format.html do
          flash[:notice] = t('forms.messages.user_was_successfully_updated')
          redirect_to @user
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    respond_to do |format|
      flash[:notice] = t('forms.messages.user_was_successfully_destroyed')
      format.html { redirect_to users_url }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  def check_if_editing_admin
    refuse_with_method_not_allowed if @user.admin && current_user.id != @user.id && !current_user.superuser
  end

  def search_query(query, page)
    [if query.any?
       User.where(query).limit(PER_PAGE).offset(PER_PAGE * page)
     else
       User.all.limit(PER_PAGE).offset(PER_PAGE * page)
     end].flatten.compact
  end

  # Only allow a list of trusted parameters through.
  def user_params
    if current_user&.superuser
      params.require(:user).permit(:username, :email, :password, :password_confirmation, :admin, :superuser)
    else
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
  end

  def redirect_to_index
    if session[:current_user_id]
      redirect_to users_path
    else
      sign_in @user
    end
  end

  def check_admin_permission
    refuse_with_method_not_allowed unless current_user.admin
  end

  def check_admin_or_self_permission
    refuse_with_method_not_allowed unless current_user.admin || current_user.id == params[:id].to_i
  end

  def update_user(submitted_user_params)
    if current_user&.admin && submitted_user_params[:password].blank?
      @user.update_columns(user_params.to_unsafe_h.except(:password))
    else
      @user.update(user_params)
    end
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_back.html.erb
<%= link_to t('forms.back'), current_user.admin ? users_path : root_path, class: 'btn btn-secondary' %>

app/views/users/_delete.html.erb
<% if current_user.superuser
  confirm_message = t('forms.messages.delete_superuser?')
elsif current_user.admin
  confirm_message = t('forms.messages.delete_admin?')
else
  confirm_message = t('forms.messages.are_you_sure?')
end %>

<%= link_to t('forms.delete'), { action: :destroy, id: user.id}, method: :delete, data: { confirm: confirm_message },
  class: small ? 'btn btn-outline-danger btn-sm' : 'btn btn-danger' %>

app/views/users/_edited.html.erb
<div>
	Изменено
</div>

app/views/users/_form.html.erb
<%= javascript_pack_tag 'checkbox_handler', 'data-turbolinks-track': 'reload'%>

<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <b><%= t 'forms.errors', count: user.errors.count %></b>
      <ul>
        <% user.errors.each do |error| %>
          <li><small>
            <%= error.full_message %>
          </small></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.label :username %>
  <%= form.text_field(:username, class: "form-control col-12", required: true) %>
  <%= form.label :email %>
  <%= form.text_field(:email, class: "form-control col-12", required: true) %>
  <%= form.label :password %>
  <%= form.password_field(:password, class: "form-control col-12", required: password_required) %>
  <% unless current_user&.admin %>
    <%= form.label :password_confirmation %>
    <%= form.password_field(:password_confirmation, class: "form-control col-12", required: password_required) %>
  <% end %>
  <% if current_user&.superuser %>
    <div class="form-check">
      <%= form.check_box :admin, class: 'form-check-input'%>
      <%= form.label :admin, class: 'form-check-label' %>
    </div>
    <div class="form-check">
      <%= form.check_box :superuser, class: "form-check-input" %>
      <%= form.label :superuser, class: "form-check-label" %>
    </div>
  <% end %>
  <%# <%= form.submit t('forms.submit'), class: "btn btn-primary col-12" %> 
  <%= form.submit t('forms.submit'), class: "btn btn-primary col-12" %>
<% end %>

app/views/users/_notEdited.html.erb
<div>
	Не изменено
</div>

app/views/users/edit.html.erb
<h1><%= t 'forms.editing_user' %></h1>

<div class="uniform-control">
  <%= render 'form', user: @user, current_user: @current_user, password_required: false %>
  <div class="btn-group col-12">
    <%= link_to t('form.show'), @user, class: 'btn btn-primary' %>
    <%= render 'back', current_user: @current_user %>
    <%= render 'delete', user: @user, current_user: @current_user, small: false %>
  </div>
  <div id="show_container"></div>
</div>

app/views/users/index.html.erb
<% flash[:notice]&.tap do |notice| %>
    <div class="alert alert-success"><%= notice %></div>
<% end %>

<div class="top-float">
  <%= link_to t('forms.new_user'), new_user_path, class: 'btn btn-outline-success col-12' %>
</div>

<h1><%= t 'forms.users' %></h1>

<%= form_with url: users_path, method: :get, class: "uniform-control" do |form| %>
  <%= form.label :username, t('activerecord.attributes.user.username') %>
  <%= form.text_field(:username, class: "form-control col-12", value: @params[:username]) %>
  <div class="btn-group col-12">
    <%= form.submit t('forms.search'), class: "btn btn-primary" %>
    <%= link_to t('forms.reset'), users_path, class: "btn btn-secondary", style: "margin-bottom: 10px" %>
  </div>
<% end %>

<h2 style="margin-left: 50px">
  <% if @params[:username].presence %>
    <%= t('forms.search_results_for') %>
    <%= t('activerecord.attributes.user.username') + ": \'#{@params[:username]}\'" if @params[:username] %>
  <% end %>
</h2>

<% if @users.none? %>
  <%= render 'nothing_found' %>
<% else %>

  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col"><%= t 'activerecord.attributes.user.username' %></th>
        <th scope="col"><%= t 'activerecord.attributes.user.email' %></th>
        <th scope="col"><%= t 'activerecord.attributes.user.admin' %></th>
        <th scope="col"><%= t 'activerecord.attributes.user.superuser' %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.username %></td>
          <td><%= user.email %></td>
          <td><%= t(user.admin ? 'yes' : 'no') %></td>
          <td><%= t(user.superuser ? 'yes' : 'no') %></td>
          <td><%= link_to t('forms.show'), user, class: 'btn btn-outline-primary btn-sm' %></td>
          <% if !user.admin || @current_user.superuser || user.id == @current_user.id %>
            <td><%= link_to t('forms.edit'), edit_user_path(user), class: 'btn btn-outline-primary btn-sm' %></td>
            <td><%= render 'delete', user: user, current_user: @current_user, small: true %></td>
          <% else %>
            <td colspan=2></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>

  <%= render 'pagination', current_page: @params[:page].to_i, pages: @pages %>
<% end %>

app/views/users/new.html.erb
<% unless @current_user %>
  <h1><%= t('forms.sign_up') %></h1>
<% else %>
  <h1><%= t('forms.new_user') %></h1>
<% end %>

<div class="uniform-control">
  <%= render 'form', user: @user, current_user: @current_user, password_required: true %>
  <% unless @current_user %>
    <%= link_to t('forms.sign_in'), signin_path, class: "btn btn-outline-primary col-12" %>
  <% else %>
    <div class="btn-group col-12">
      <%= render 'back', current_user: @current_user %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h1><%= t('forms.account') %></h1>

<div class="uniform-control">
  <% flash[:notice]&.tap do |notice| %>
      <div class="alert alert-success"><%= notice %></div>
  <% end %>

  <p>
    <strong><%= t('activerecord.attributes.user.username') %>:</strong>
    <%= @user.username %>
  </p>

  <p>
    <strong><%= t('activerecord.attributes.user.email') %>:</strong>
    <%= @user.email %>
  </p>

  <p>
    <strong><%= t('activerecord.attributes.user.admin') %>:</strong>
    <%= @user.admin ? 'Yes' : 'No' %>
  </p>

  <p>
    <strong><%= t('activerecord.attributes.user.superuser') %>:</strong>
    <%= @user.superuser ? 'Yes' : 'No' %>
  </p>

  <div class="btn-group col-12">
  <% unless @user.admin && !@current_user.superuser && !(@user.id == @current_user.id) %>
    <%= link_to t('forms.edit'), edit_user_path(@user), class: 'btn btn-primary'%>
  <% end %>
  <%= render 'back', current_user: @current_user %>
  </div>
</p>

app/views/users/show.turbo_stream.erb
<% if @flag %>
	<%= turbo_stream.update 'show_container', partial: 'edited' %>
<% else %>
	<%= turbo_stream.update 'show_container', partial: 'notEdited' %>
<% end %>