config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :pastes
  resources :users
  resources :sessions, only: %i[new create destroy]
  get '/signin', to: 'sessions#new'
  get '/signup', to: 'users#new'
  root 'pastes#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/paste.rb
# frozen_string_literal: true

class Paste < ApplicationRecord
  before_save :set_default_values
  belongs_to :user, optional: true
  validates_presence_of :content
  validates_inclusion_of :private, in: [false], if: :anonymous?, message: 'pastes can only be created once logged in'

  def set_default_values
    self.language = 'plaintext' if language.blank?
  end

  def anonymous?
    user.nil?
  end
end

app/controllers/pastes_controller.rb
# frozen_string_literal: true

LANGUAGES = JSON.parse(File.read("#{Rails.root}/public/languages.json"))

# Pastes controller
class PastesController < ApplicationController
  before_action :set_paste, only: %i[show edit update destroy]
  before_action :check_modify_access, only: %i[edit update destroy]
  before_action :check_view_access, only: %i[show]
  skip_before_action :authenticate, only: %i[new create show]

  # GET /pastes
  def index
    @pastes = search_query({
      name: params[:name].presence,
      user_id: @current_user&.admin ? find_user_id(params[:username]) : @current_user
    }.compact, params[:page].to_i || 0)
  end

  # GET /pastes/1
  def show; end

  # GET /pastes/new
  def new
    @paste = Paste.new
  end

  # GET /pastes/1/edit
  def edit; end

  # POST /pastes
  def create
    @paste = Paste.new(paste_params)
    @paste.user = current_user
    respond_to do |format|
      if @paste.save
        format.html { redirect_to @paste, notice: t('forms.messages.paste_was_successfully_created') }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pastes/1
  def update
    @flag = true
    respond_to do |format|
      if @paste.update(paste_params)
        format.html { redirect_to @paste, notice: t('forms.messages.paste_was_successfully_updated') }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pastes/1
  def destroy
    @paste.destroy
    respond_to do |format|
      format.html { redirect_to pastes_url, notice: t('forms.messages.paste_was_successfully_destroyed') }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.

  def set_paste
    @paste = Paste.find(params[:id])
  end

  def check_view_access
    refuse_with_method_not_allowed unless !@paste.private || current_user&.admin || @paste.user == current_user
  end

  def check_modify_access
    refuse_with_method_not_allowed unless current_user&.admin || @paste.user == current_user
  end

  def find_user_id(username)
    nil unless username.presence
    User.find_by(username: username)&.id
  end

  def search_query(query, page)
    if query.key?(:user_id) && !query[:user_id]
      []
    else
      [if query.any?
         Paste.where(query).limit(PER_PAGE).offset(PER_PAGE * page)
       else
         Paste.all.limit(PER_PAGE).offset(PER_PAGE * page)
       end].flatten.compact
    end
  end

  # Only allow a list of trusted parameters through.
  def paste_params
    params.require(:paste).permit(:name, :content, :language, :private)
  end
end

app/helpers/pastes_helper.rb
# frozen_string_literal: true

module PastesHelper
end

app/views/pastes/_back.html.erb
<%= link_to t('forms.back'), pastes_path, class: 'btn btn-secondary' %>

app/views/pastes/_form.html.erb
<div class="side-padded">
  <%= form_with(model: paste) do |form| %>
    <% if paste.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <b><%= t 'forms.errors', count: paste.errors.count %></b>
        <ul>
          <% paste.errors.each do |error| %>
            <li><small>
              <%= error.full_message %>
            </small></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div style="width: calc(100% - 450px); position: absolute; top: 152px; bottom: 50px; right: 20px">
      <%= form.label :content %>
      <%= form.text_area :content, class: 'form-control', style: 'resize: none; height: 100%',
                                   placeholder: t('forms.content_placeholder'), autofocus: true, autocomplete: 'off'%>
    </div>
    <div class="inner-control">
      <%= form.label :name %>
      <%= form.text_field :name, class: 'form-control', placeholder: t('activerecord.attributes.paste.untitled'), autocomplete: 'off' %>
      <%= form.label :language %>
      <%= form.select :language, LANGUAGES, { include_blank: false }, class: 'form-select' %>
    </div>
    <% if current_user %>
      <div class="form-check">
        <%= form.label :private, t('activerecord.attributes.paste.private?'), class: 'form-check-label' %>
        <%= form.check_box :private, class: 'form-check-input' %>
      </div>
    <% end %>
    
    <%= form.submit value: t('forms.submit'),  class: 'btn btn-primary inner-control' %>
  <% end %>
</div>

app/views/pastes/edit.html.erb
<h1><%= t 'forms.editing_paste' %></h1>

<%= render 'form', paste: @paste, current_user: @current_user %>
<div class="btn-group col-12 uniform-control">
  <%= link_to t('forms.show'), @paste, class: 'btn btn-primary' %>
  <%= render 'back' %>
  <%= link_to t('forms.delete'), @paste, method: :delete, data: { confirm: t('forms.messages.are_you_sure?') }, class: 'btn btn-danger' %>
</div>

app/views/pastes/index.html.erb
<% flash[:notice]&.tap do |notice| %>
    <div class="alert alert-success"><%= notice %></div>
<% end %>

<div class="top-float">
  <%= link_to t('forms.new_paste'), new_paste_path, class: 'btn btn-outline-success col-12' %>
</div>

<h1><%= t 'forms.pastes' %></h1>

<div class="uniform-control">
  <%= form_with url: pastes_path, method: :get do |form| %>
    <%= form.label :name, t('activerecord.attributes.paste.name') %>
    <%= form.text_field(:name, class: "form-control col-12", value: @params[:name]) %>
    <% if @current_user.admin %>
      <%= form.label :username, t('activerecord.attributes.paste.owner') %>
      <%= form.text_field(:username, class: "form-control col-12", value: @params[:username]) %>
    <% end %>
    <div class="btn-group col-12">
      <%= form.submit t('forms.search'), class: "btn btn-primary" %>
      <%= link_to t('forms.reset'), pastes_path, class: "btn btn-secondary", style: "margin-bottom: 10px" %>
    </div>
  <% end %>
</div>

<h2 style="margin-left: 50px">
  <% if request_name = @params[:name].presence || request_username = @params[:username].presence %>
    <%= t('forms.search_results_for') %>
    <% if @params[:name].presence %>
      <%= t('activerecord.attributes.paste.name') + ": \'#{@params[:name]}\'" if @params[:name] %>
    <% end %>
    <% if @params[:username].presence %>
      <%= t('activerecord.attributes.paste.owner') + ": \'#{@params[:username]}\'" if @params[:username] %>
    <% end %>
  <% end %>
</h2>

<% if @pastes.none? %>
  <%= render 'nothing_found' %>
<% else %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th><%= t('activerecord.attributes.paste.name') %></th>
        <th><%= t('activerecord.attributes.paste.language') %></th>
        <th><%= t('activerecord.attributes.paste.private') %></th>
        <th><%= t('activerecord.attributes.paste.owner') %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @pastes.each do |paste| %>
        <tr>
          <td><%= !paste.name&.presence ? t('activerecord.attributes.paste.untitled') : paste.name %></td>
          <td><%= LANGUAGES.find { |pair| pair.last == paste.language }.first %></td>
          <td><%= t "activerecord.attributes.paste.#{paste.private ? 'private!' : 'public!'}" %></td>
          <td><%= paste.anonymous? ? t('forms.anonymous') : paste.user.username %></td>
          <td><%= link_to t('forms.show'), paste, class: 'btn btn-outline-primary btn-sm' %></td>
          <td><%= link_to t('forms.edit'), edit_paste_path(paste), class: 'btn btn-outline-primary btn-sm' %></td>
          <td><%= link_to t('forms.delete'), paste, method: :delete, data: { confirm: t('forms.messages.are_you_sure?') }, class: 'btn btn-outline-danger btn-sm' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= render 'pagination', current_page: @params[:page].to_i, pages: @pages %>
<% end %>

app/views/pastes/new.html.erb
<h1><%= t 'forms.new_paste' %></h1>

<%= render 'form', paste: @paste, current_user: @current_user %>

app/views/pastes/show.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/prismjs@1.25.0/themes/prism.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/prismjs@1.25.0/plugins/line-numbers/prism-line-numbers.css">
<script src="https://cdn.jsdelivr.net/npm/prismjs@1.25.0/components/prism-core.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/prismjs@1.25.0/plugins/autoloader/prism-autoloader.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/prismjs@1.25.0/plugins/line-numbers/prism-line-numbers.min.js"></script>

<h1><%= @paste.name.empty? ? t('activerecord.attributes.paste.untitled') : @paste.name %></h1>
<div style="float: left;" class="uniform-control">
  <% flash[:notice]&.tap do |notice| %>
      <div class="alert alert-success"><%= notice %></div>
  <% end %>

  <p>
    <strong><%= t('activerecord.attributes.paste.language') %>:</strong>
    <%= LANGUAGES.find { |pair| pair.last == @paste.language }.first %>
  </p>

  <p>
    <strong><%= t('activerecord.attributes.paste.private') %>:</strong>
    <%= t "activerecord.attributes.paste.#{@paste.private ? 'private!' : 'public!'}" %>
  </p>
  <p>
    <strong><%= t('activerecord.attributes.paste.owner') %>:</strong>
    <%= @paste.anonymous? ? t('forms.anonymous') : @paste.user.username %>
  </p>

  <div class="btn-group col-12">
  <% if @current_user&.==(@paste.user) || @current_user&.admin %>
    <%= link_to t('forms.edit'), edit_paste_path(@paste), class: 'btn btn-primary' %>
  <% end %>
    <%= render 'back' %>
  </div>
</div>
<div style="float: left; padding: 20px; width: calc(100% - 450px)">
  <button class="btn btn-outline-success" id="btn-copy"><%= t 'forms.copy' %></button>
  <pre><code class="line-numbers language-<%= @paste.language %>"><%= @paste.content %></code></pre>
</div>

<script>
  text = `<%= @paste.content.html_safe %>`;
</script>

<%= javascript_pack_tag 'copy_handler', 'data-turbolinks-track': 'reload' %>